### PR TITLE
Fix crafting

### PR DESCRIPTION
**Pull request by kuba6000**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7368

### CODE REVIEW

**Comment by Dream-Master** [comment]
Please change build gradle version to 1.2.7 in build.grade and it builds again.

**Comment by repo-alt** [comment]
what will this do with crafting using damageable tools?

**Comment by kuba6000** [comment]
It's still gonna work as intended. This check was completely unnecessary and causing non damageable items such as filled buckets to be voided.

**Review by repo-alt — APPROVED** [review]
ok then

**Pull request merged**
