### PR TITLE
Add StorageDrawers compat

### PR DESCRIPTION
**Pull request by makamys**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3393

### CODE REVIEW

**Comment by repo-alt** [comment]
This is a backport too, right?

**Comment by Dream-Master** [comment]
@makamys

**Comment by makamys** [comment]
Yeah, it's a backport of the behavior with drawers on newer versions. In the 1.11 version it was implemented by using Forge's capability API, but that didn't exist yet in 1.7.10 so I added explicit support for storage drawers.

**Comment by makamys** [comment]
In 1.7.10, Forge didn't have any kind of standard for inventories with non-standard stack sizes, so what PR had to do was add specific support for mods. The reason why JABBA barrels worked with request pipes was because when the container is a barrel, it uses a special class for handling it, `DeepStorageInvWrapper` (actually, it interfaces with MFR's deep storage interface, which barrels also implement).
What I did was follow this line of thought and add `StorageDrawersInvWrapper` to handle interfacing with storage drawer inventories.

Forge later got the capability API in 1.8, which made this kind of mod-specific support no longer necessary. Once PR implemented it, it automatically got compatibility with every storage mod that also respects the API.

**Comment by moller21** [comment]
Thanks alot :)

**Pull request merged**
